### PR TITLE
Move uniform.css demos and use all available uni-components

### PR DESCRIPTION
**Pull request by alshakero**
Only `<uni-form-item-group>` is left to do. I'll do it tomorrow after Omni meeting.

Requires installing `uniform.css` from master to work. 

Fixes https://github.com/Starcounter/UniformDocs/issues/318

The issue is unclear. So I did all the obvious (and most time consuming) but work and some questions remain that need easy work. Will there then still be separate `uniform.css` docs? Or we're copying everything and removing them from there? This PR assumes yes. If not, I'd appreciate some document or comment that describes what goes where.

### CODE REVIEW

**Comment by warpech** [comment]
> Will there then still be separate uniform.css docs?

There  will be no separate Uniform.css docs. But the `index.html` files can be kept for testing purposes.

**Comment by alshakero** [comment]
I'm now adding an example of `<uni-form-item-group>` and after that it should be reviewable.

**Comment by alshakero** [comment]
Should be ready. Although requires `uniform.css#0.4.0`.

**Comment by warpech** [comment]
I have merged PR #328 into here. It includes an up-to-date demo of `uni-date-picker`.

**Comment by alshakero** [comment]
Merging as [released ](https://github.com/Starcounter/UniformDocs/releases/tag/3.1.0)and [deployed](https://uniform.starcounter.io/).

**Pull request merged**
