### PR TITLE
Try every test only once unless asked otherwise

### PR DESCRIPTION
**Pull request by alshakero**
See https://github.com/Starcounter/UniformDocs/issues/324

### CODE REVIEW

**Comment by alshakero** [comment]
@kegor ping.

**Comment by alshakero** [comment]
I would love to do that and do it like all other tests. But then we'd have a lot of repeated code for the same element and the same expected behaviour. 

> This PR is a workaround for the previous workaround. We should not be building piles of workarounds.

This PR removes the workaround for all other tests except `GitHubSourceLinks`, I see it more like it mostly cancels the other workaround. And BTW, `waitUntil` natively has an option to ignore this exception, 
By doing: 
```csharp
wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(StaleElementReferenceException));
```
and it's a very common scenario. But this feature is broken in Selenium so I implemented my own exception ignoring setup. 

See https://github.com/SeleniumHQ/selenium/issues/4240

And commit history here, https://github.com/Starcounter/UniformDocs/pull/331#commits-pushed-1c24e7f

**Comment by warpech** [comment]
This PR should be retargeted to `master` (which is equivalent to was was `master-2.4` until now) or a new PR should be made.

**Comment by warpech** [comment]
@alshakero and @kegor WDYT of closing this PR without merging? I never fully understand the reason for this change, but I can tell that the tests of UniformDocs have not been flaky for very long time, so this PR might be not needed.

**Comment by kegor** [comment]
From one side I agree with @warpech in the sense that if tests running ok on TC and locally then we don't have reasons to make any fixes, but from another side i didn't understand fully the case of running these tests in which @alshakero met the problem and what kind of problem. Maybe this problem isn't actual with using `BrowserStack` at nowdays?

**Comment by alshakero** [comment]
I think this PR can be closed without merging.

**Pull request closed without merging**
